version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    ports:
      - "9042:9042" # Cassandra default port
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
